export type EducationHealthAnalysis = {
  bmiValue: number;
  bmiStatus: "Kurang" | "Normal" | "Overweight" | "Obesitas" | "Belum ada data";
  activityStatus: "Aktif" | "Cukup aktif" | "Kurang aktif" | "Sangat kurang aktif" | "Belum ada data";
  hydrationStatus: "Cukup" | "Perlu ditambah" | "Belum ada data";
  sleepStatus: "Cukup" | "Kurang" | "Berlebih" | "Belum ada data";
  bloodPressureStatus: "Rendah" | "Normal" | "Waspada" | "Tinggi" | "Belum ada data";
  heartRateStatus: "Rendah" | "Normal" | "Tinggi" | "Belum ada data";
  dataAvailability: "Belum ada data" | "Terbatas" | "Cukup";
  overallStatus: "Baik" | "Perlu dipantau" | "Perlu perhatian" | "Belum ada data";
  overallRecommendation: string;
  educationalNotes: string[];
};

export type EducationSourceData = {
  patientName: string;
  age?: string | number;
  gender?: string;
  location?: string;
  height?: number;
  weight?: number;
  bmi?: number;
  bloodPressure?: string;
  bloodPressureStatus?: string;
  heartRate?: number;
  heartRateStatus?: string;
  steps?: number;
  waterGlasses?: number;
  mealCalories?: number;
  mealSummary?: string;
  activitySummary?: string;
  hydrationSummary?: string;
  sleepSummary?: string;
  sleepHours?: number;
  sleepStatus?: string;
  sleepHistorySummary?: string;
  recentBloodPressureSummary?: string;
  recentStepSummary?: string;
  recentHydrationSummary?: string;
  recentMealComparisonSummary?: string;
  recentHydrationComparisonSummary?: string;
  recentActivityComparisonSummary?: string;
  recentWeightBmiSummary?: string;
  recentSleepComparisonSummary?: string;
  recentHeartRateSummary?: string;
  recentMostChangedSummary?: string;
  recentHistorySummary?: string;
  recentTrendSummary?: string;
  prioritySummary?: string;
  recentMeasurementSummary?: string;
  recentActivitySummary?: string;
  recentNutritionSummary?: string;
  latestMeasurementAt?: string;
};

export type EducationPromptContext = {
  patientName: string;
  age: string;
  gender: string;
  height: string;
  weight: string;
  location: string;
  healthSummary: string;
  recentHistorySummary: string;
  recentTrendSummary: string;
  prioritySummary: string;
  recentMeasurementSummary: string;
  recentActivitySummary: string;
  recentNutritionSummary: string;
  sleepSummary: string;
  bloodPressure: string;
  bloodPressureStatus: string;
  heartRate: string;
  heartRateStatus: string;
  dataAvailability: string;
  activitySummary: string;
  mealSummary: string;
  hydrationSummary: string;
  sleepHours: string;
  sleepStatus: string;
  sleepHistorySummary: string;
  recentBloodPressureSummary: string;
  recentStepSummary: string;
  recentHydrationSummary: string;
  recentMealComparisonSummary: string;
  recentHydrationComparisonSummary: string;
  recentActivityComparisonSummary: string;
  recentWeightBmiSummary: string;
  recentSleepComparisonSummary: string;
  recentHeartRateSummary: string;
  recentMostChangedSummary: string;
  predictionSummary: string;
};

export type EducationContext = {
  educationContext: EducationPromptContext;
  analysis: EducationHealthAnalysis;
  promptSummary: string;
};
